const CREATE_USER = 10
const UPDATE_USER = 20
const DELETE_USER = 30
const UNKNOWN_USER = 40
const SUCCESS_AUTHENTIFICATION_USER = 50
const INVALID_EMAIL_OR_PASSWORD = 60
const INVALID_EMAIL_PASSWORD_FORMAT = 70
const USER_ALREADY_EXISTS = 80
const INCOMPELETE_DATA = 90

module.exports = {
  CREATE_USER,
  SUCCESS_AUTHENTIFICATION_USER,
  UPDATE_USER,
  UNKNOWN_USER,
  DELETE_USER,
  INVALID_EMAIL_OR_PASSWORD,
  INVALID_EMAIL_PASSWORD_FORMAT,
  USER_ALREADY_EXISTS,
  INCOMPELETE_DATA
}