env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides:
  - files: "*.js"
    rules:
      strict: off
      "no-console": "warn"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - node
rules: {}

